# OR

In [18]:
import numpy as np

In [19]:
X = [[0,0],[1,0],[0,1],[1,1]] 
t = [0,1,1,1]

In [20]:
w = [1,2]
b = 1
np.dot(w,X[1])+b

2

In [21]:
def perc(x) :
    f = np.dot(w,x)+b
    if f>=0 :
        y=1
    else :
        y=0
    return y

In [22]:
perc_f=[]
for i in range(4):
    perc_f.append(perc(X[i]))

In [23]:
perc_f==np.array(t)

array([False,  True,  True,  True])

In [24]:
eta = 0.1
for n in range(1000):
    error_sum = 0
    for i in range(4):
        error = t[i]-perc(X[i])
        error_sum = abs(error_sum)+abs(error)
        
        w[0]=w[0] + eta*error*X[i][0]
        w[1]=w[1] + eta*error*X[i][1]
        b= b + eta*error
    if(error_sum==0):
        break    

In [25]:
w,b

([1.0, 2.0], -0.09999999999999987)

In [29]:
perc_f=[]
for i in range(4):
    perc_f.append(perc(X[i]))

In [30]:
perc_f==np.array(t)

array([ True,  True,  True,  True])

# Iris classifications

In [33]:
import numpy as np

In [34]:
from sklearn import datasets
iris = datasets.load_iris()
iris.target_names
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [35]:
X = iris.data

In [36]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [37]:
y = np.where(iris.target>0,1,0)

In [38]:
w=[1,1,1,1]
b = 1
np.dot(w,X[1])+b

10.5

In [39]:
perc_f=[]
for i in range(150):
    perc_f.append(perc(X[i]))

In [40]:
perc_f== y

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

In [41]:
def perc(x) :
    f = np.dot(w,x)+b
    if f>=0 :
        y=1
    else :
        y=0
    return y  

In [42]:
eta = 0.1
for n in range(1000):
    error_sum = 0
    for i in range(150):
        error = y[i]-perc(X[i])
        error_sum = abs(error_sum)+abs(error)
        
        w[0]=w[0] + eta*error*X[i][0]
        w[1]=w[1] + eta*error*X[i][1]
        w[2]=w[2] + eta*error*X[i][2]
        w[3]=w[3] + eta*error*X[i][3]
        b= b + eta*error
    if(error_sum==0):
        break     

In [43]:
w, b

([-0.4700000000000001, 0.029999999999999805, 0.59, 0.94], 0.7000000000000001)

In [44]:
perc_f=[]
for i in range(150):
    perc_f.append(perc(X[i]))

In [45]:
perc_f== y

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,